#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to Consul running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YzRkNjYxMmY0YjZmYWY0YzgxMzJmMWY1NjBkMmVjMjRiOWI5MWYyYzA2OGU1OTAxM2I0NTllYmE4Y2M1MmFhNmY3NDliNGQ5MDM3MmY5NzExY2UyY2MxN2I1N2U3NmQzYjIzYw==
