configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjZiNTMwZmVmYmVjZDViMWMxYmI4ZjdhMTI0Zjg5MmI1M2FmYTk2NTFhY2JjNWJmZWFjNGU1Y2NkMzhhODdiZGExYWRkNWE2NjhmMmQ4MGU5MDYwNDM3YzdkMzI4ZjBlMmUwMGY3NjIyZWM3YWY0NjgzZDJmYmU3YjkyYzk0MTA=
