apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: demo
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: ZGRlNTgyNzBmMDg5Mjk3ZmMxMTlkOWU1Yjc5MGQyNjY0N2JmNGEwODc1NTg4OTJiOWM2YmE0M2M1ZWMwMzIwN2EzZDhlNjIxZmI0M2EyYmM1YjAyYjIxOGQ0MWM3NTNmYjhjNA==
  # app specific configuration
